CREATE ROLE kakeibon WITH LOGIN;
CREATE DATABASE kakeibon;
GRANT CONNECT ON DATABASE kakeibon TO kakeibon;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT ON DATABASE kakeibon FROM PUBLIC;
GRANT CONNECT ON DATABASE kakeibon TO kakeibon;
CREATE SCHEMA kakeibon AUTHORIZATION kakeibon;
GRANT USAGE ON SCHEMA kakeibon TO kakeibon;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA kakeibon TO kakeibon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA kakeibon TO kakeibon;
ALTER ROLE kakeibon SET search_path TO "KakeiBon";

