SELECT SUM(INCLUSIVE_TAX) AS TOTAL_AMOUNT
FROM
  (
    SELECT 
      TAX_TYPE, TAX_RATE, CAST(TOTAL_AMOUNT AS VARCHAR) AS TOTAL_AMOUNT,
      ROUND(TOTAL_AMOUNT * RATE) AS INCLUSIVE_TAX
    FROM
    (
      SELECT CAST(TT.TAX_TYPE AS VARCHAR) AS TAX_TYPE,
        CAST(TR.TAX_RATE AS VARCHAR) AS TAX_RATE,
        SUM(D.EXCLUDE_TAX) AS TOTAL_AMOUNT,
        CAST(1 + (CAST(TR.TAX_RATE AS NUMERIC)::NUMERIC(10, 2) / 100) AS NUMERIC)::NUMERIC(10,2) AS RATE
      FROM
        DETAILS D
        JOIN TAX_TYPE TT ON D.USER_ID = TT.USER_ID AND D.TAX_TYPE_ID = TT.TAX_TYPE_ID
        JOIN TAX_RATE TR ON D.USER_ID = TR.USER_ID AND D.TAX_RATE_ID = TR.TAX_RATE_ID
      WHERE D.USER_ID = 2 AND D.HEADER_ID = 10
      GROUP BY TT.TAX_TYPE, TR.TAX_RATE
    )
  )
-- UNION ALL
-- SELECT
--   '合計', '税率', '税別', SUM(D.EXCLUDE_TAX)
-- FROM DETAILS AS D
-- WHERE D.USER_ID = 2
-- AND D.HEADER_ID = 10
;

