SELECT HEADER_ID, DETAIL_ID, SUM(INCLUSIVE_TAX) AS TOTAL_AMOUNT 
FROM (
  SELECT HEADER_ID, DETAIL_ID, TAX_TYPE, TAX_RATE, CAST(TOTAL_AMOUNT AS VARCHAR) AS TOTAL_AMOUNT, 
         TRUNC(TOTAL_AMOUNT * RATE) AS INCLUSIVE_TAX 
  FROM (
    SELECT D.HEADER_ID AS HEADER_ID, D.DETAIL_ID AS DETAIL_ID, CAST(TT.TAX_TYPE AS VARCHAR) AS TAX_TYPE, CAST(TR.TAX_RATE AS VARCHAR) AS TAX_RATE,
           SUM(D.EXCLUDE_TAX) AS TOTAL_AMOUNT,
           1 + (CAST(TR.TAX_RATE AS REAL) / 100) AS RATE
    FROM DETAILS D
    JOIN TAX_TYPE TT ON D.USER_ID = TT.USER_ID AND D.TAX_TYPE_ID = TT.TAX_TYPE_ID
    JOIN TAX_RATE TR ON D.USER_ID = TR.USER_ID AND D.TAX_RATE_ID = TR.TAX_RATE_ID
    WHERE D.USER_ID = :pUserID AND D.HEADER_ID = :pHeaderID
    GROUP BY D.HEADER_ID, D.DETAIL_ID, TT.TAX_TYPE, TR.TAX_RATE
  )
)
